require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollisionsController do

  # This should return the minimal set of attributes required to create a valid
  # Collision. As you add validations to Collision, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "date_of_collision" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollisionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all collisions as @collisions" do
      collision = Collision.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collisions).should eq([collision])
    end
  end

  describe "GET show" do
    it "assigns the requested collision as @collision" do
      collision = Collision.create! valid_attributes
      get :show, {:id => collision.to_param}, valid_session
      assigns(:collision).should eq(collision)
    end
  end

  describe "GET new" do
    it "assigns a new collision as @collision" do
      get :new, {}, valid_session
      assigns(:collision).should be_a_new(Collision)
    end
  end

  describe "GET edit" do
    it "assigns the requested collision as @collision" do
      collision = Collision.create! valid_attributes
      get :edit, {:id => collision.to_param}, valid_session
      assigns(:collision).should eq(collision)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Collision" do
        expect {
          post :create, {:collision => valid_attributes}, valid_session
        }.to change(Collision, :count).by(1)
      end

      it "assigns a newly created collision as @collision" do
        post :create, {:collision => valid_attributes}, valid_session
        assigns(:collision).should be_a(Collision)
        assigns(:collision).should be_persisted
      end

      it "redirects to the created collision" do
        post :create, {:collision => valid_attributes}, valid_session
        response.should redirect_to(Collision.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collision as @collision" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collision.any_instance.stub(:save).and_return(false)
        post :create, {:collision => { "date_of_collision" => "invalid value" }}, valid_session
        assigns(:collision).should be_a_new(Collision)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collision.any_instance.stub(:save).and_return(false)
        post :create, {:collision => { "date_of_collision" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collision" do
        collision = Collision.create! valid_attributes
        # Assuming there are no other collisions in the database, this
        # specifies that the Collision created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Collision.any_instance.should_receive(:update).with({ "date_of_collision" => "MyString" })
        put :update, {:id => collision.to_param, :collision => { "date_of_collision" => "MyString" }}, valid_session
      end

      it "assigns the requested collision as @collision" do
        collision = Collision.create! valid_attributes
        put :update, {:id => collision.to_param, :collision => valid_attributes}, valid_session
        assigns(:collision).should eq(collision)
      end

      it "redirects to the collision" do
        collision = Collision.create! valid_attributes
        put :update, {:id => collision.to_param, :collision => valid_attributes}, valid_session
        response.should redirect_to(collision)
      end
    end

    describe "with invalid params" do
      it "assigns the collision as @collision" do
        collision = Collision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collision.any_instance.stub(:save).and_return(false)
        put :update, {:id => collision.to_param, :collision => { "date_of_collision" => "invalid value" }}, valid_session
        assigns(:collision).should eq(collision)
      end

      it "re-renders the 'edit' template" do
        collision = Collision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collision.any_instance.stub(:save).and_return(false)
        put :update, {:id => collision.to_param, :collision => { "date_of_collision" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collision" do
      collision = Collision.create! valid_attributes
      expect {
        delete :destroy, {:id => collision.to_param}, valid_session
      }.to change(Collision, :count).by(-1)
    end

    it "redirects to the collisions list" do
      collision = Collision.create! valid_attributes
      delete :destroy, {:id => collision.to_param}, valid_session
      response.should redirect_to(collisions_url)
    end
  end

end
